<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author Brent Shaffer
 */
class PluginCategoryTable extends Doctrine_Table
{
  /**
   * Get a category by name
   *
   * @param string $name The category name
   *
   * @return Category
   **/
  public function getCategory($name)
  {
    if (!is_string($name))
    {
      throw new sfException('You must pass a string as an argument');
    }

    $category = $this->findOneByName($name);
    return $category;
  }

  /**
   * Get a category by name, and create it if it doesn't exists already
   *
   * @param string $name The category name
   *
   * @return Category
   **/
  public function getOrCreateCategory($name)
  {
    $category = $this->findOneByName($name);
    if (!$category)
    {
      $category = new Category();
      $category['name'] = $name;
      $category->save();
    }

    return $category;
  }

  /**
   * Get all categories in the category subtree (root included)
   *
   * @param string $parentName
   *
   * @return Doctrine_Collection
   **/
  public function getSubTreeCategories($parentName)
  {
    $parent = $this->findOneByName($parentName);

    if (!$parent instanceOf Category)
      return null;

    $children = $parent->getSubCategories();
    if(!$children)
    {
      $children = new Doctrine_Collection('Category');
    }
    $children->add($parent);
    return $children;
  }
}
