<?php

/**
 * PluginCategoryObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    csDoctrineActAsCategorizablePlugin
 * @subpackage model
 * @author     Thibault Jouannic <thibault@jouannic.fr>
 */
abstract class PluginCategoryObject extends BaseCategoryObject
{

}
