<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/27 13:24:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:////var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/data/test.sqlite',
  'name' => 'doctrine',
)),);
