<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/02/27 13:28:27
return array(

  // csDoctrineActAsCategorizablePlugin_module_libs

  // csDoctrineActAsCategorizablePlugin_lib
  'doctrine_template_categorizable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/template/Categorizable.php',
  'categoryrefclassgenerator' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/generator/CategoryRefClassGenerator.class.php',
  'plugincategoryobjectform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/form/doctrine/PluginCategoryObjectForm.class.php',
  'plugincategoryform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/form/doctrine/PluginCategoryForm.class.php',
  'doctrine_template_listener_categorizable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/listener/Categorizable.php',
  'plugincategoryformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/filter/doctrine/PluginCategoryFormFilter.class.php',
  'plugincategoryobjectformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/filter/doctrine/PluginCategoryObjectFormFilter.class.php',
  'plugincategoryobject' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/model/doctrine/PluginCategoryObject.class.php',
  'plugincategory' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/model/doctrine/PluginCategory.class.php',
  'plugincategorytable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/model/doctrine/PluginCategoryTable.class.php',
  'plugincategoryobjecttable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/lib/model/doctrine/PluginCategoryObjectTable.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinerecord' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineexception' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrineroutecollection' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineformgenerator' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegenerator' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinecolumn' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfformdoctrine' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecli' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinemigratetask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuildtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinedqltask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebasetask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'swift_doctrinespool' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrineconnectionlistener' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sftesterdoctrine' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinepager' => '/var/www/sftest/lib/vendor/symfony-1.4.1/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',

  // project
  'articleform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/doctrine/ArticleForm.class.php',
  'baseformdoctrine' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/doctrine/BaseFormDoctrine.class.php',
  'categoryform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/doctrine/csDoctrineActAsCategorizablePlugin/CategoryForm.class.php',
  'basecategoryform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/doctrine/csDoctrineActAsCategorizablePlugin/base/BaseCategoryForm.class.php',
  'basearticleform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/doctrine/base/BaseArticleForm.class.php',
  'baseform' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/form/BaseForm.class.php',
  'articleformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/filter/doctrine/ArticleFormFilter.class.php',
  'baseformfilterdoctrine' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'categoryformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/filter/doctrine/csDoctrineActAsCategorizablePlugin/CategoryFormFilter.class.php',
  'basecategoryformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/filter/doctrine/csDoctrineActAsCategorizablePlugin/base/BaseCategoryFormFilter.class.php',
  'basearticleformfilter' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/filter/doctrine/base/BaseArticleFormFilter.class.php',

  // project_model
  'article' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/Article.class.php',
  'category' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/Category.class.php',
  'basecategory' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/base/BaseCategory.class.php',
  'basecategoryobject' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/base/BaseCategoryObject.class.php',
  'categoryobjecttable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/CategoryObjectTable.class.php',
  'categoryobject' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/CategoryObject.class.php',
  'categorytable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/csDoctrineActAsCategorizablePlugin/CategoryTable.class.php',
  'articletable' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/ArticleTable.class.php',
  'basearticle' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/lib/model/doctrine/base/BaseArticle.class.php',

  // application
  'myuser' => '/var/www/sftest/plugins/csDoctrineActAsCategorizablePlugin/test/fixtures/project/apps/frontend/lib/myUser.class.php',

  // modules
);
