Category:
  actAs:
    NestedSet:
      hasManyRoots:   true
  columns:
    id:
      type:           integer
      autoincrement:  true
      primary:        true
    name:
      type:           string(255)
    description:
      type:           clob
